# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
 branches:
   include:
     - '*' # Trigger builds on all branches

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: $(Date:yyyy).$(Date:MM).$(Date:dd).$(BuildID)

steps:
- task: NuGetToolInstaller@0
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '/aeea8857-f430-496d-a11b-5968b96e1107'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**\AssemblyInfo.cs'
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Title: 'UMN SCCM Application Categorization Tool'
    Product: 'UMN SCCM Application Categorization Tool'
    Description: 'A tool to quickly manage which applications are in which catagories in SCCM.'
    Company: 'University of Minnesota'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '1.0.*.*'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: '**\Microsoft.ConfigurationManagement.ManagementProvider.dll*'

- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: '**\AdminUI.WqlQueryEngine.dll*'

- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.BinariesDirectory)'
    Contents: 'UMN-SCCMApplicationCategorization\bin\Release\**\**'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)\UMN-SCCMApplicationCategorization\bin\Release'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)'
    ArtifactName: 'source'
